spring:
  application:
    name: usian-sso-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.32.130:7001
        - 192.168.32.130:7002
        - 192.168.32.130:7003
        - 192.168.32.130:7004
        - 192.168.32.130:7005
        - 192.168.32.130:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
server:
  port: 8098
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#sso
SESSION_EXPIRE: 604800
USER_INFO: USER_INFO
