spring:
  application:
    name: usian-order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.32.130:7001
        - 192.168.32.130:7002
        - 192.168.32.130:7003
        - 192.168.32.130:7004
        - 192.168.32.130:7005
        - 192.168.32.130:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  rabbitmq:
    host: 192.168.32.132
    username: admin
    password: 1111
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    publisher-confirms: true #开启响应返回
    publisher-returns: true #开启消息退回回调
server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY
SETNX_ORDER_LOCK_KEY: SETNX_ORDER_LOCK_KEY
LOCK_TIMES: 100
