spring:
  application:
    name: usian-cart-service
  redis:
    cluster:
      nodes:
        - 192.168.32.130:7001
        - 192.168.32.130:7002
        - 192.168.32.130:7003
        - 192.168.32.130:7004
        - 192.168.32.130:7005
        - 192.168.32.130:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#购物车
CART_REDIS_KEY: CART_REDIS_KEY
CART_COOKIE_EXPIRE: 604800
